<?php

namespace AppBundle\Repository;

/**
 * AssignmentLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
