<?php

namespace AppBundle\Repository;

/**
 * ClockMomentLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClockMomentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
