<?php

namespace AppBundle\Repository;

/**
 * EmployeeLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
