<?php

namespace AppBundle\Repository;

/**
 * LargeDataLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LargeDataLogRepository extends \Doctrine\ORM\EntityRepository
{
}
