<?php

namespace AppBundle\Repository;

/**
 * SystemConfigLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemConfigLogRepository extends \Doctrine\ORM\EntityRepository
{
}
