<?php

namespace AppBundle\Enumerator;

/**
 * Class CompanyXUserRole.
 */
abstract class CompanyXUserRole
{
	const ADMINISTRATORS = 'ROLE_ADMINISTRATORS';
	const TELEPHONELIST_ACCESS = 'ROLE_TELEPHONELIST_ACCESS';
	const COMMUNICATION_CENTRE = 'ROLE_COMMUNICATION_CENTRE';
	const CREATING_SCHEDULES = 'ROLE_CREATING_SCHEDULES';
	const ALL_RIGHTS = 'ROLE_ALL_RIGHTS';
	const NEWSLETTER_CREATION = 'ROLE_NEWSLETTER_CREATION';
	const HOURS = 'ROLE_HOURS';
	const HOURS_REGISTER = 'ROLE_HOURS_REGISTER';
	const HOURS_ACCORD = 'ROLE_HOURS_ACCORD';
	const VACATION_MANAGEMENT = 'ROLE_VACATION_MANAGEMENT';
	const EMPLOYEES = 'ROLE_EMPLOYEES';
	const EMPLOYEES_LOOKING_NOT_EDITING = 'ROLE_EMPLOYEES_LOOKING_NOT_EDITING';
	const EMPLOYEES_CONTROL = 'ROLE_EMPLOYEES_CONTROL';
	const MANAGEMENT = 'ROLE_MANAGEMENT';
	const MANAGEMENT_DASHBOARD = 'ROLE_MANAGEMENT_DASHBOARD';
	const MANAGEMENT_DIARY = 'ROLE_MANAGEMENT_DIARY';
	const MANAGEMENT_AGENDA = 'ROLE_MANAGEMENT_AGENDA';
	const MANAGEMENT_FORECAST = 'ROLE_MANAGEMENT_FORECAST';
	const MANAGEMENT_EVERYTHING = 'ROLE_MANAGEMENT_EVERYTHING';
	const REPORTS = 'ROLE_REPORTS';
	const CREATING_PERMISSIONS = 'ROLE_CREATING_PERMISSIONS';
	const SHOW_SALARIES = 'ROLE_SHOW_SALARIES';
	const HIDE_SALARIES = 'ROLE_HIDE_SALARIES';
	const GROUP_PERMISSIONS = 'ROLE_GROUP_PERMISSIONS';
	const GROUP_PERMISSIONS_FOR_EMPLOYEES = 'ROLE_GROUP_PERMISSIONS_FOR_EMPLOYEES';
	const GROUP_PERMISSIONS_FOR_VISITOR = 'ROLE_GROUP_PERMISSIONS_FOR_VISITOR';
	const GROUP_PERMISSIONS_FOR_EVERYONE = 'ROLE_GROUP_PERMISSIONS_FOR_EVERYONE';
	const GROUP_PERMISSIONS_FOR_PRE_MEMBER = 'ROLE_GROUP_PERMISSIONS_FOR_PRE_MEMBER';
	const SUPER_USER = 'ROLE_SUPER_USER';
}
